import type { Metadata } from "next";
import { Inter, Noto_Sans_JP, Oswald } from "next/font/google";
import "./globals.css";
import Footer from "@/components/navigation/footer";
import MainNavigation from "@/components/navigation/main-navigation";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CompanyX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // These additions persist on all pages, currently main navigation at the top and footer at the bottom
    <html lang="en">
      <body
        className={`${oswald.variable} ${inter.variable} ${notoSansJP.variable} antialiased`}
      >
        <div className="min-h-screen grid grid-rows-[auto_1fr_auto]">
          <MainNavigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
